### ISSUE TITLE
No tests

### ISSUE THREAD

**Issue by jamiew** [bo-oz/vimeo_me2#3]
Time to add some :)

What is the state-of-the-art for remote HTTP request mocking? Is it still VCR and family?

**Comment by bo-oz** [comment]
I will look into your suggestions. I think the tests could be pretty straightforward. Will try to spend some time this weekend.

**Comment by jamiew** [comment]
Yep agreed. I'm out of town but happy to help out next week

**Comment by bo-oz** [comment]
Any suggestions on how to set-up the initial requests without exposing my private key? Is Vimeo maybe offering some kind of testing API key with access to all API methods?

**Comment by jamiew** [comment]
Good question. @agilefox @dasheron is there a Vimeo API best practice for this? Register a test application maybe?

**Comment by bo-oz** [comment]
I think I found a solution, upon first request VCR records the response. After that I can clean the test code of any private info (like token). Tests keep passing because the response is replayed anyway. Will be pushing some intial testsuite set-up later this week (maybe tomorrow). Maybe we can join forces from there. Thanks.

**Comment by bo-oz** [comment]
@jamiew I added a basic set-up for testing, maybe you can have a look? I kept my (old) private key in the source, but I guess that invalidating that one from Vimeo Developer does the trick right?

**Comment by jamiew** [comment]
Yep you can just get rid of it later. These look great 👍
